### ISSUE TITLE
[1.5] The script collected xxx points missing from logs

### ISSUE THREAD

**Issue by mgrimace** [TheNetsky/Microsoft-Rewards-Script#226]
I no longer get 'the script collected xxx points today' log item. I have `parallel=true` and `clusters=2`.

Adding `await` log does not fix it. Perhaps because of parallel being true, or due to it appearing in the mobile part of index.ts? Potentially worth a look as it would make a great notification. Adding as a separate issue because I buried it in my notification testing issue #90 

```ts
        const afterPointAmount = await this.browser.func.getCurrentPoints()

        log(this.isMobile, 'MAIN-POINTS', `The script collected ${afterPointAmount - this.pointsInitial} points today`)

        // Close mobile browser
        await this.browser.func.closeBrowser(browser, account.email)
        return
    }

}
```

**Comment by TheNetsky** [comment]
I think that's fixed by https://github.com/TheNetsky/Microsoft-Rewards-Script/pull/228

**Comment by mgrimace** [comment]
> I think that's fixed by [#228](https://github.com/TheNetsky/Microsoft-Rewards-Script/pull/228)

Tested the fix above, and I still don't have any log line that says 'the script collected'. Would it make sense to move it out of mobile and into runTasks instead in the index.ts?

I do have parallel and clusters on in case that's messing with things.

**Comment by AariaX** [comment]
![Screenshot_2025-02-09-12-28-57-50_64ef5fc2000c1caa954c114bb372e1d5.jpg](https://github.com/user-attachments/assets/10912e2b-6a73-4d65-b7fa-4d27b02bed3f)

Working fine for me

**Comment by mgrimace** [comment]
> ![Screenshot_2025-02-09-12-28-57-50_64ef5fc2000c1caa954c114bb372e1d5.jpg](https://github.com/user-attachments/assets/10912e2b-6a73-4d65-b7fa-4d27b02bed3f)
> 
> Working fine for me

huh, are you using parallels and/or clusters? I can't imagine why it wouldn't even show in my logs if it should be

**Comment by AariaX** [comment]
> > ![Screenshot_2025-02-09-12-28-57-50_64ef5fc2000c1caa954c114bb372e1d5.jpg](https://github.com/user-attachments/assets/10912e2b-6a73-4d65-b7fa-4d27b02bed3f)
> > 
> > Working fine for me
> 
> huh, are you using parallels and/or clusters? I can't imagine why it wouldn't even show in my logs if it should be

4 clusters non parallel

**Comment by mgrimace** [comment]
> 4 clusters non parallel

confirming now that the issue is with parallel enabled/`true`. I tested it off, and it generated the log item and notification.

When parallel is enabled, the log entry for 'the script collected...' does not appear

**Comment by TheNetsky** [comment]
> > 4 clusters non parallel
> 
> confirming now that the issue is with parallel enabled/`true`. I tested it off, and it generated the log item and notification.
> 
> When parallel is enabled, the log entry for 'the script collected...' does not appear

Is there any other message you get instead?
Example `Unable to complete mobile searches, bad User-Agent? Increase search delay? Retrying...` instead?

**Comment by mgrimace** [comment]
> > > 4 clusters non parallel
> > 
> > 
> > confirming now that the issue is with parallel enabled/`true`. I tested it off, and it generated the log item and notification.
> > When parallel is enabled, the log entry for 'the script collected...' does not appear
> 
> Is there any other message you get instead? Example `Unable to complete mobile searches, bad User-Agent? Increase search delay? Retrying...` instead?

As far as I can tell it just doesn't appear, no errors or other messages. I'll double check

**Comment by AariaX** [comment]
Tested with parallels on, log still appear for me

**Comment by mgrimace** [comment]
Ah ok, I think I narrowed it down: the initial run *DOES* show the points with parallels on/off. Subsequent runs on the same day, do not show points (for me). I was testing the script so much I had already gained points, and the following runs weren't showing anything. I'll close the issue but I have two suggestions:

- consider moving this out of 'mobile' and into tasks in index.ts
- consider a 'zero' points if it's not in there already

Unfortunately, I don't know enough about the syntax of index.ts to do this myself without hopelessly breaking it.

**Comment by TheNetsky** [comment]
I mean Mobile is always ran after Desktop, regardless if it's set up to do searches or not.

And if it cannot gather points, since they've all been completed it should show "No points to earn and "runOnZeroPoints" is set to "false", stopping!" unless of course "runOnZeroPoints" is enabled, if that is enabled it should show the final count.

**Comment by mgrimace** [comment]
> I mean Mobile is always ran after Desktop, regardless if it's set up to do searches or not.
> 
> And if it cannot gather points, since they've all been completed it should show "No points to earn and "runOnZeroPoints" is set to "false", stopping!" unless of course "runOnZeroPoints" is enabled, if that is enabled it should show the final count.

That makes sense, and I'll add a notification for 'no points to earn', appreciate that lead thanks!
